### ISSUE TITLE
Add additional plugins to CNI

### ISSUE THREAD

**Issue by PhracturedBlue** [mgoltzsche/podman-static#17]
Is there a reason you limited the plugin to CNI to just bridge and portmap?
To make things easier, it would be nice to have the tuning and firewall plugins (since these are used by podman by default when creating a new network), but I see no reason not to build all of them.

Will you entertain a pull-request to add more plugins?

**Comment by mgoltzsche** [comment]
In order to keep the image small, it contains only the CNI plugins that are required by default, assuming users could add plugins for their particular use cases, if needed, by building a new image based on the one shipped by this repo.
However, since podman configures the `tuning` and `firewall` plugins by default for a network and because this came up in #11 as well, those two plugins should be [added](https://github.com/mgoltzsche/podman-static/blob/v3.2.3/Dockerfile#L57) to the image and tar indeed. A PR would be welcome.
