### ISSUE TITLE
What would it take to include systemd?

### ISSUE THREAD

**Issue by skoppe** [mgoltzsche/podman-static#45]
Right now journald is not available as a logging driver, which makes running rootless podman in Nomad difficult.

I assume for journald logging driver to be available, the lib needs to be available when building.

**Comment by mgoltzsche** [comment]
> I assume for journald logging driver to be available, the lib needs to be available when building.

Exactly. However systemd/journald is not available on alpine so that you'd need to build it from source but, if I remember correctly, it relies on glibc functionality that is not available within the musl libc that comes with alpine. (alpine is used to build the static binary since it is optimized for being statically linked.) Also, even if you'd manage to build the systemd/journald library on alpine, linking it into podman statically would increase the binary's size tremendously.

**Comment by skoppe** [comment]
I see, thank you for the quick response. I am going to try to find another way to install a recent-ish version of podman.
