### ISSUE TITLE
looking forward to auto-restart capability when node reboot

### ISSUE THREAD

**Issue by panpan0000** [mgoltzsche/podman-static#48]
background: https://github.com/kubernetes-sigs/kind/issues/2998

```
the podman-restart.service should be included on Podman 4.4.0 and onwards
https://github.com/containers/podman/pull/16672
https://github.com/containers/podman/issues/16669
```

So I guess two works need to be done:
(1) upgrade podman from 4.2.1 to 4.4.0
(2) include the `podman-restart` service  in static release

**Comment by panpan0000** [comment]
I just download `podman-4.3.1-1.1.x86_64.rpm`, there's `/usr/lib/systemd/system/podman-restart.service`  in the package.

**Comment by mgoltzsche** [comment]
@panpan0000 so as I understand you want the `podman-restart` systemd service to be redistributed by this repository.

Currently this does not make sense to me because the container image and binaries shipped by this repository explicitly don't support systemd and are built primarily to run on systems without systemd.
Also, it looks like restarting a podman container is the caller's responsibility, not the responsibility of podman itself. (This makes sense since podman is not designed as a daemon like containerd/dockerd.)
If you want to make podman containers restart on boot, you have to run those additonal commands somehow on boot or, if you're using systemd as init system, simply download the [`podman-restart.service` template](https://github.com/containers/podman/blob/1933972909bdf2fd7b1d282431c3c6f7b00cfe49/contrib/systemd/system/podman-restart.service.in#L12).

Regarding the update: podman 4.4.0 is not stable yet but the latest stable podman update 4.3.1 should also be shipped by this repo indeed.

**Comment by mgoltzsche** [comment]
I am closing this issue now. In case you have strong argument for redistributing the systemd unit with the tar within this repo, feel free to reopen the issue.

**Comment by panpan0000** [comment]
got you @mgoltzsche . Thank you for your response !

**Comment by mgoltzsche** [comment]
Release [v4.4.4](https://github.com/mgoltzsche/podman-static/releases/tag/v4.4.4) provides `/usr/lib/systemd/system/podman-restart.service` with the tar archive
