### ISSUE TITLE
Request to add buildah and skopeo

### ISSUE THREAD

**Issue by srbala** [mgoltzsche/podman-static#6]
@mgoltzsche This is not an issue. Request to add static `buildah` and `skopeo` packages, might be as another package like `podman-tools` or `build-tools`

https://github.com/containers/buildah 
https://github.com/containers/skopeo

**Comment by mgoltzsche** [comment]
@srbala initially this repository's podman image provided `buildah` and `skopeo` binaries but I removed them in favour of a more minimalistic image that could be extended when needed as opposed to a fat image that contains everything somebody may need eventually (see #1).
Why do you need skopeo within the podman image? podman can pull/push/copy images as well using the same library skopeo uses. I think unless you rely on buildah CLI commands podman does not expose you also don't need buildah when you're working with podman already which has buildah built-in as a library since podman 2. Though of course there are cases where you'd still favour buildah over podman but in that case you can use a separate buildah image (e.g. the official `quay.io/buildah/stable` image).

**Comment by srbala** [comment]
@mgoltzsche thank you for quick response. I agree to the idea of build as needed.
