### ISSUE TITLE
about crun/catatonit

### ISSUE THREAD

**Issue by fantastic2085** [mgoltzsche/podman-static#75]
The package downloaded from this link(https://github.com/mgoltzsche/podman-static/releases/tag/v4.4.4) does not include crun/catatonit,  Do I need to download from 2 links (https://github.com/containers/crun / https://github.com/openSUSE/catatonit)

**Comment by mgoltzsche** [comment]
The archive that is attached to the release does contain the `catatonit` binary at `/usr/local/lib/podman/catatonit`. Though, it does not contain the `crun` binary but `runc` (at `/usr/local/bin/runc`). If you really need `crun` instead of `runc`, you could for instance extract it from the minimal container image (`ghcr.io/mgoltzsche/podman:4.8.1-minimal`) published by this repo.

**Comment by fantastic2085** [comment]
If I want to use crun, download it from this link(ghcr.io/mgoltzsche/podman:4.8.1-minimal) instead of crun's github(https://github.com/containers/crun ), am I understanding it correctly

**Comment by mgoltzsche** [comment]
I meant you could extract the `crun` binary from the `ghcr.io/mgoltzsche/podman:4.8.1-minimal` image but as I just realized within #77 the crun binary within the minimal image doesn't work on arm64 machines but on amd64 machines only.
However, since the image build also simply downloads the binary from the [crun](https://github.com/containers/crun) release you linked, you could as well get if from there - they also provide an arm64 binary is that's what you need.

**Comment by mgoltzsche** [comment]
I added the `crun` binary to the normal (non-minimal) podman image and tar distribution now. It should be published with the 5.1.1-1 release later today. Thus, I am closing this issue. Please feel free to re-open it if something is still unclear.
