### ISSUE TITLE
about crun-linux-amd64-disable-systemd

### ISSUE THREAD

**Issue by fantastic2085** [mgoltzsche/podman-static#77]
![image](https://github.com/mgoltzsche/podman-static/assets/4116773/e1e03ff1-7541-4cee-bf56-0bbdae1294b8)

See the crun for downloading linux-amd64-disable-systemd from dokcerfile. Why

**Comment by mgoltzsche** [comment]
Which problem do you mean? :sweat_smile: 
1. Now that you point it out, I realize it is always downloading an amd64 version of crun which prevents the minimal image from running on arm64 systems which should otherwise work. That should be fixed by downloading the arm64 instead of the amd64 binary when building for the arm64 architecture! (The tests within this repo are run against the amd64 container only.)
2. The container image shipped by this repo contains only binaries that are compiled without systemd support. That is because a) the container is based on alpine which doesn't ship systemd (and you'd have problems building it yourself due to musl libc) and b) the binaries within the container should be statically linked in order to be able to copy and run them on any linux amd64/arm64 system and statically linking them with systemd would really bloat them.
