### ISSUE TITLE
about storage.conf

### ISSUE THREAD

**Issue by fantastic2085** [mgoltzsche/podman-static#78]
I installed podman in ubuntu22.04 and compared it to Podman-static
![image](https://github.com/mgoltzsche/podman-static/assets/4116773/7085632d-6595-4998-9fb9-6853b6e0f631)

1. Why is ignore_chown_errors set to true
2. Why set fsync=0 for mountopt
3. Why is mount_program not commented out

Can I modify it as follows:
#ignore_chown_errors = "false"
#mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,metacopy=on"

**Comment by mgoltzsche** [comment]
Except for the containers.conf, all configuration files are used for both images shipped by this repository: the rootful/normal podman container and the rootless/minimal podman container. That's why the configuration is optimized for rootless podman. Also, I must admit I didn't touch the configuration files for a long time during updates. Regarding your questions:
1. If I remember correctly, this was necessary to make rootless podman work (at least at the time of writing). For rootful podman that is not necessary.
2. I don't know for sure. I may have copied that from an old podman version or it was also because of an issue with rootless podman at the time.
3. I also did that to make rootless podman work (overlayfs is implemented within the kernel space and the best user-space alternative is fuse-overlayfs).

A rootful podman should work with your config changes.

**Comment by mgoltzsche** [comment]
I am closing this issue since the question was answered.
Please feel free to re-open or create another issue if anything is unclear.
