### ISSUE TITLE
missing the crun binary

### ISSUE THREAD

**Issue by ErikJiang** [mgoltzsche/podman-static#88]
podman version: v4.9.4

![image](https://github.com/mgoltzsche/podman-static/assets/10629406/a3325f05-63db-496c-b108-fc8662dfc6de)

In the v4.9.4 version of the tar package, 

it was found that the binary file for `crun` is missing. 

Previous versions also had similar issues.

**Comment by mgoltzsche** [comment]
The `crun` binary never was within the tar package because the tar package is based on the regular container image that comes with `runc` instead of `crun`, not the one with the `minimal` tag that comes with `crun`.
`crun` is a lightweight OCI runtime implementation and alternative to `runc`. `crun` is particularly useful when you want to run containers with minimal isolation such as required in very restricted environments or when running nested containers.
I didn't think it would make sense to ship both `crun` and `runc` with the tar distribution because most of the time users would want to use only one OCI runtime per installation and `runc` would be way to go for tar users since it is the reference implementation and more feature complete than `crun`. Correspondingly, while you can use `crun` with docker, it is not installed with docker by default but `runc` is. Personally, I am using only `runc` on my host but `crun` in nested containers.
Is `runc` not sufficient for your host installation use-case?

**Comment by ErikJiang** [comment]
https://github.com/mgoltzsche/podman-static/blob/v4.9.4/Dockerfile#L166-L181

I noticed the step in the Dockerfile where crun is being downloaded, 
so I assumed that crun would also be part of the tar package. 
It seems that my understanding was incorrect. 
please correct me if I'm wrong. thank you.

**Comment by mgoltzsche** [comment]
Both the minimal and  the regular image are built from the same Dockerfile. The `rootlesspodmanminimal` stage/target build is published as the `minimal` image which contains the `crun` binary as opposed to the last stage within the Dockerfile that is published as regular image.

**Comment by ErikJiang** [comment]
@mgoltzsche  Thank you for your explanation. 🤝

**Comment by mgoltzsche** [comment]
FYI: For convenience the crun binary is now also contained within the regular (non-minimal) image as well as within the tar distribution.
